config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :images
  root 'posts#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_posts, dependent: :destroy
  has_many :posts, through: :category_posts
  validates :name, :thumb, presence: true
end

app/models/category_post.rb
class CategoryPost < ApplicationRecord
  belongs_to :category
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, presence: true, length: { maximum: 20 }
  validates :content, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :category_posts, dependent: :destroy
  has_many :categories, through: :category_posts
  validates :title, :content, :description, :keywords, presence: true
  validates :description, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.order('created_at DESC')
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to categories_path
    else 
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  
  
  private
  def category_params
    params.require(:category).permit(:name, :thumb)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @categories = @post.categories.order('created_at DESC')
    @comment = @post.comments.build(comment_params)
    if @comment.save && admin_signed_in?
      redirect_to post_path(@comment.post_id)
    elsif admin_signed_in?
      @comments = @post.comments.order('created_at DESC')
      render 'posts/show' 
    elsif @comment.save
      redirect_to post_path(@comment.post_id)
    else
      @comments = @post.comments.order('created_at DESC')
      render 'posts/show'
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(params[:post_id])
    redirect_to post_path(@post)
  end
  
  
  private
    def comment_params
      params.require(:comment).permit(:post_id, :name, :content )
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @images = Image.all
  end
  
  def new
    @image = Image.new
  end
  
  def create
    @image = Image.create(image_params)
    if @image.save
      redirect_to images_path
    else
      render 'new'
    end
  end
  
  def edit
    @image = Image.find(params[:id])
  end
  
  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to images_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end
  
  private
  def image_params
    params.require(:image).permit(:name, :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @post = Post.page(params[:page]).per(10).order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order('created_at DESC')
    @categories = @post.categories.order('created_at DESC')
    @url = request.url
  end

  def new
    @post = Post.new
    @post.category_posts.build
  end
  
  def create
    @post = Post.create(post_params)
    if @post.save then
      redirect_to posts_path
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params) then
      redirect_to post_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  def after_sign_in_path_for(resource)
      posts_path
  end
  
  
  private
  def post_params
    params.require(:post).permit(:title, :content, :thumb, :description, :keywords, { :category_ids=> [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # meta_tagに関するヘルパー
  def default_meta_tags
    {
      site: "Green-Onyx",
      title: "",
      reverse: true,
      charset: "utf-8",
      description: "web制作に関してほとんど知識が無かったrails初心者が自身のアウトプットの為に作ったブログです。",
      keywords: "Green-Onyx,green-onyx,birdman,プログラミング",
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url("favicon.ico") },
        { href: image_url("icon.jpg"), rel: "apple-touch-icon", sizes: '180x180', type: "image/jpg" },
      ],
      og: {
        site_name: "Green-Onyx",
        title: "Green-Onyx",
        description: "web制作に関してほとんど知識が無かったrails初心者が自身のアウトプットの為に作ったブログです。",
        type: 'blog',
        url: request.original_url,
        image: image_url("ogp.png"),
        locale: "ja_JP",
      },
      twitter: {
        card: "summary",
        site: "@Birdman_yk_",
        creator: "@Birdman_yk_",
        domain: "8green-onyx8.com",
        title: "Green-Onyx",
        description: "web制作に関してほとんど知識が無かったrails初心者が自身のアウトプットの為に作ったブログです。",
      }
    }
  end
  
  # 年月日時分のみ表示するヘルパー
  def simple_time(time)
    time.strftime("%Y-%m-%d %H:%M ")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/markdowns_helper.rb
module MarkdownsHelper
  require 'redcarpet'
  require 'coderay'

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0]

      case language.to_s
        when 'rb'
          lang = 'ruby'
        when 'yml'
          lang = 'yaml'
        when 'css'
          lang = 'css'
        when 'html'
          lang = 'html'
        when ''
          lang = 'md'
        else
          lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

   def markdown(text)
    html_render = HTMLwithCoderay.new( with_toc_data: true)

    option = {
        autolink: true,
        space_after_headers: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        lax_html_blocks: true,
        strikethrough: true
    }

    markdown = Redcarpet::Markdown.new(html_render, option)
    markdown.render(text)
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_errors-message.html.erb
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |err| %>
    <%= err %>
  <% end %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<div class="category-name">
  <h1><%= f.label :name, "カテゴリー名" %></h1>
  <%= f.text_field :name, class: "name-input" %>
</div>
<div class="category-thumb">
  <h1><%= f.label :thumb, "サムネイルURL" %></h1>
  <%= f.text_field :thumb, class: "category-url" %>
</div>
  <%= f.submit "作成" %>
<% end %>

app/views/categories/edit.html.erb
<% set_meta_tags noindex: true %>

<%= render 'categories/errors-message' %>
<%= render 'categories/form' %>

app/views/categories/index.html.erb
<% set_meta_tags title: "タグ", og: { title: "タグ", type: 'blog' }, twitter: { title: "タグ" } %>
<div class="categories-index">
  <h1>タグ一覧</h1>
  
  <div class="categories">
    <ul>
      <% @categories.each do |category| %>
        <li>
          <%= link_to category_path(category) do %>
            <%= image_tag "#{category.thumb}" %>
            <h2><%= category.name %></h2>
          <% end %>
        </li>
      <% end %>
    </ul>
  
  
    <div class="admin-menu">
      <% if admin_signed_in? %>
        <%= link_to "新規作成", new_category_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<% set_meta_tags noindex: true %>
<%= render 'categories/errors-message' %>
<%= render 'categories/form' %>

app/views/categories/show.html.erb
<% set_meta_tags title: @category.name, og: { title: @category.name, type: 'blog' }, twitter: { title: @category.name } %>
<div class="categories-show">
  <h1>"<%= @category.name %>"のタグがついた記事</h1>
  <div class="categories">
    <% if admin_signed_in? %>
      <div class="admin-menu">
        <%= link_to "編集", edit_category_path(@category.id) %>
        <%= link_to "削除", category_path(@category.id), method: :delete, data: {confirm: "削除しますか？"} %>
      </div>
    <% end %>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to post_path(post.id) do %>
            <%= image_tag "#{post.thumb}" %>
            <h2><%= post.title %></h2>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="form-container">
  <div class="comment-err">
    <% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |err| %>
        <p><%= err %></p>
      <% end %>
    <% end %>
  </div>

    <%= form_for([@post, @comment]) do |f| %>
      <%= f.hidden_field :post_id %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "comment-author", placeholder: "※必須項目　20文字以内" %>
      <%= f.label :content, "コメント" %>
      <%= f.text_area :content, class: "comment-body", placeholder: "※必須項目" %>
      <%= f.submit "投稿する", class: "submit-btn" %>
    <% end %>

</div>

app/views/comments/_index.html.erb
<h2>コメント</h2>
<% @comments.each do |comment| %>
<div class="comment-entries">
  <div class="comment-author">
    <%= simple_format(comment.name) %>
  </div>
  <div class="comment-date">
    <i class="far fa-clock fa-fw"></i>
    <%= simple_time(comment[:created_at]) %>
  </div>
  <div class="comment-body">
    <%= simple_format(comment.content) %>
  </div>
  
  <% if admin_signed_in? %>
    <div class="comment-admin-menu">
      <%= link_to "削除", post_comment_path(comment.post_id, comment.id),
                          method: :delete, data: {confirm: "削除しますか？"} %>
    </div>
  <% end %>
</div>
<% end %>

app/views/images/_errors-message.html.erb
<% if @image.errors.any? %>
  <% @image.errors.full_messages.each do |err| %>
    <%= err %>
  <% end %>
<% end %>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :name, "イメージネーム" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/images/edit.html.erb
<% set_meta_tags noindex: true %>
<%= render 'images/errors-message' %>
<%= render 'images/form' %>

app/views/images/index.html.erb
<% set_meta_tags noindex: true %>
<%= link_to "画像追加", new_image_path %>
<% @images.each do |i| %>
  <p><%= i.name %></p>
  <%= i.image.url %>
  <%= image_tag i.image.to_s %>
  <%= link_to "編集", edit_image_path(i.id) %>
  <%= link_to "削除", image_path(i.id), method: :delete, data: {confirm: "削除しますか？"} %>
<% end %>

app/views/images/new.html.erb
<% set_meta_tags noindex: true %>
<%= render 'images/errors-message' %>
<%= render 'images/form' %>

app/views/layouts/_footer.html.erb
<p>© 2018 Green-Onyx.com</p>

app/views/layouts/_header.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<span class="logo"><%= render 'layouts/logo' %></span>
  <div id="nav-drawer">
    <input id="nav-input" type="checkbox" class="nav-unshown">
    <label id="nav-open" for="nav-input"><i class="fas fa-bars fa-2x"></i></label>
    <label class="nav-unshown" id="nav-close" for="nav-input"><i class="fas fa-times-circle fa-2x"></i></label>
  <div id="nav-content">
    <ul>
    <% if admin_signed_in? %>
      <%= link_to new_post_path do %>
      <li>
        <i class="fas fa-plus-circle fa-fw"></i><span>新規作成</span>
      </li>
      <% end %>
      <%= link_to edit_admin_registration_path do %>
        <li>
          <i class="fas fa-user fa-fw"></i><span>プロフィール</span>
        </li>
      <% end %>
      <%= link_to destroy_admin_session_path, method: :delete do %>
        <li>
          <i class="fas fa-sign-out-alt fa-fw"></i><span>ログアウト</span>
        </li>
      <% end %>
    <% end %>
      <%= link_to categories_path do %>
        <li>
          <i class="fas fa-tags fa-fw"></i><span>タグ一覧</span>
        </li>
      <% end %>
      <%= link_to root_path do%>
        <li>
          <i class="fas fa-home fa-fw"></i><span>ホーム</span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_logo.html.erb
<svg id="logo1" data-name="logo1" xmlns="http://www.w3.org/2000/svg" width="368" height="88" viewBox="0 0 368 88" style="">
  <metadata>
   <rdf:rdf xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:description rdf:about=""></rdf:description>
   </rdf:rdf>
  </metadata>
<defs>

  </defs>
  <path id="logo2" data-name="logo2" class="logo-path PeviIHmq_1" d="M56,43S68.124,29.621,75,25c-1.33,2.021-15.012,6.336,4,9C56.983,53.857,67.368,60.68,82,47c5.644,2.927,7.173,4.292,11,4,23.365,2.053,18.284-24.534-4-5-9,6.834-9.329,20.073,14,12,8.871-2.8,19.051-3.443,25-4,15.522-7.981.576-16.431-11-4-4.152,5.007-8.82,19.281,11,14,7.512-3.523,16.2-12.675,19-18-4.494,12.309-10.177,19.466-8,20,6.671-4.351,18.125-21.536,25-19-15.984,28.13-3.872,23.418,10,12"></path>
  <path id="logo3" data-name="logo3" class="logo-path PeviIHmq_2" d="M230,30c1.341,0.114-26.244-2.345-23,30,6.351,21.416,31.792,14.048,41-7s-3.262-44.223-34-27c-13.055,10.2-12.963,22.361-13,25"></path>
  <path id="logo4" data-name="logo4" class="logo-path PeviIHmq_3" d="M265,41l-3,23s14.393-24.055,18-26c-10.265,36.544,9.982,14.762,15,11s9.511-14.32,10-15c-15.337,28.235.411,27.781,14-5,7.142-12.852-3.306,47.653-13,55-5.4,4.22-14.337-2.9,0-18,9.453-8.454,26.781-26.173,32-40,6.392-2.3,5.323,5.418,13,15,7.287,4.307,12.749-4.471,14-14"></path>
  <path id="logo5" data-name="logo5" class="logo-path PeviIHmq_4" d="M358,19s-23.381,26.1-23,46"></path>
  <path id="logo1" data-name="logo1" class="logo-path PeviIHmq_0" d="M57,12S49.43-6.049,17,7C-3.087,17.476-12.123,60.629,54,28c5.557-1.565-25.1,36.777-35,40C3.633,76.107-6.708,62.233,17,51c7.492-3.809,22.387-9.1,35-5"></path>
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google analytics-->
    <%= analytics_init if Rails.env.production? %>
    <!-- Realtime preview -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>  
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script> 
    <!-- Fontawesome -->
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!--favicon-->
    <%= favicon_link_tag("favicons/favicon.ico") %>
    <!--apple-->
    <%= favicon_link_tag("favicons/green-onyx-icon.png",
                         {:rel => "apple-touch-icon",
                          :sizes => "180x180",
                          :type => "image/png"}) %>
  </head>

  <body>
    <div class="wrapper">
      <header><%= render 'layouts/header' %></header>
      <div class="main"><%= yield %></div>
      <footer><%= render 'layouts/footer' %></footer>
    </div>
  </body>
</html>

app/views/posts/_errors-message.html.erb
<div class="post-err">
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |err| %>
      <p><%= err %></p>
    <% end %>
  <% end %>
</div>

app/views/posts/_post-form.html.erb
<%= form_for(@post) do |f| %>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :name, class: 'categories' %>
<div class="post-title">
  <h1><%= f.label :title, "タイトル" %></h1>
  <%= f.text_field :title, class: "title-input" %>
</div>
<div class="post-thumb">
  <h1><%= f.label :thumb, "サムネイルURL" %></h1>
  <%= f.text_field :thumb, class: "thumb-url" %>
</div>
<div class="post-keywords">
  <%= f.label :keywords, "meta_tag_key_words" %>
  <%= f.text_area :keywords, class: "keywords-input" %>
</div>
<div class="post-description">
  <%= f.label :description, "meta_tag_description" %>
  <%= f.text_area :description, class: "description-input" %>
</div>
<div id='editor'>
  <div class="input">
  <h1><%= f.label :content, "本文" %></h1>
  <%= f.text_area :content, "v-model" => "input", "debounce" => "50", class: "content-input" %>
  </div>
  <div class="output" v-html='input | marked'></div>
</div>
<%= f.submit %>
<% end %>


<script type="text/javascript">
  window.onload = function() {
    new Vue({
      el: '#editor',
      data: {
        input: '<%== j @post.content %>',
      },
      filters: {
        marked: marked,
      },
    });
  };
</script>

app/views/posts/edit.html.erb
<% set_meta_tags noindex: true %>
<%= render 'posts/errors-message' %>
<%= render 'posts/post-form' %>

app/views/posts/index.html.erb
<% @post.each do |post| %>
  <section class="index-box">
    <%= link_to post_path(post) do %>
      <%= image_tag "#{post.thumb}"%>
      <h2><%= post.title %></h2>
      <span>
        <i class="far fa-clock fa-fw"></i><%= simple_time(post[:created_at]) %>
      </span>
    <% end %>
  </section>
<% end %>

<%= paginate @post %>

app/views/posts/new.html.erb
<% set_meta_tags noindex: true %>
<%= render 'posts/errors-message' %>
<%= render 'posts/post-form' %>

app/views/posts/show.html.erb
<% set_meta_tags title: @post.title, description: @post.description, keywords: @post.keywords,
           og: { title: @post.title, type: 'blog', description: @post.description, image: @post.thumb }, 
           twitter: { title: @post.title, description: @post.description } %>
<section class="article">
  <div class="article-header">
    <div class="article-img">
      <%= image_tag "#{@post.thumb}" %>
      <%#777777= render 'layouts/icon' %>
    </div>
    <div class="article-title">
      <h1><%= @post.title %></h1>
      <div class="article-date">
        <p><i class="far fa-clock fa-fw"></i><%= simple_time(@post[:created_at]) %></p>
        <% @categories.each do |category| %>
          <div class="article-categories">
              <%= link_to category.name, category_path(category) %>
          </div>
        <% end %>
        <% if admin_signed_in? %>
          <div class="admin-menu">
            <%= link_to "編集", edit_post_path(@post.id) %>
          </div>
          <div class="admin-menu">
            <%= link_to "削除", post_path(@post.id), method: :delete, data: {confirm: "削除しますか？"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="article-content">
    <%= markdown(@post.content).html_safe %>
  </div>
  <div class="twitter-share">
    <a href="https://twitter.com/intent/tweet?url=<%= @url %>&text=<%= @post.title %>">シェアする</a>
  </div>
</section>
<section class="comments">
  <%= render 'comments/index' %>
  <%= render 'comments/form' %>
</section>